_target_: src.models.base_module.BaseLitModule

net:
  _target_: src.models.components.cdnetv1.CDnetV1
  num_classes: 2
  in_channels: 3

criterion:
  _target_: torch.nn.CrossEntropyLoss

optimizer:
  _target_: torch.optim.SGD
  _partial_: true
  lr: 0.0001

scheduler: null

# compile model for faster training with pytorch 2.0
compile: false
