name: cloudseg
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8.0
  - pytorch=2.4.0
  - torchvision=0.19.0
  - pip=24.2
  - pip:
      - lightning==2.3.3
      - torchmetrics==1.4.1
      - hydra-core==1.3.2
      - hydra-optuna-sweeper==1.2.0
      - hydra-colorlog==1.2.0
      - rich==13.7.1
      - pytest==8.3.2
      - rootutils==1.0.7
      - wandb==0.17.5
      - aim==3.23.0
      - gradio==4.40.0
      - image-dehazer==0.0.9
      - thop==0.1.1.post2209072238
      - albumentations==1.4.13
      - segmentation_models_pytorch==0.3.3
      - gpustat==1.1.1
      - einops==0.8.0
      - tensorboard==2.14.0
      - yacs==0.1.8