name: cloudseg

channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.8.0
  - pytorch=2.0.0
  - torchvision=0.15.0
  - lightning==2.0.0
  - pip=24.2
  
  - pip:
      - torchmetrics
      - hydra-core
      - hydra-optuna-sweeper
      - hydra-colorlog
      - rich
      - pytest
      - rootutils
      - wandb
      - aim
      - gradio
      - image-dehazer
      - thop
      - albumentations
      - segmentation_models_pytorch