_target_: src.models.cdnetv2_module.CDNetv2LitModule

net:
  _target_: src.models.components.cdnetv2.CDnetV2
  num_classes: 2
  in_channels: 3

criterion:
  _target_: src.loss.cdnetv2_loss.CDnetv2Loss
  loss_fn:
    _target_: torch.nn.CrossEntropyLoss

optimizer:
  _target_: torch.optim.SGD
  _partial_: true
  lr: 0.0001

scheduler: null