_target_: src.models.base_module.BaseLitModule

net:
  _target_: src.models.components.hrcloudnet.HRCloudNet
  num_classes: 2
  in_channels: 3


criterion:
  _target_: torch.nn.CrossEntropyLoss

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.00005
  weight_decay: 0.0005

scheduler: null