_target_: src.models.rsam_seg.RSAMSegLitModule

net:
  _target_: src.models.components.rsam_seg.sam.SAM
  inp_size: 256
  loss: iou
  encoder_mode:
    name: sam
    img_size: 256
    mlp_ratio: 4
    patch_size: 16
    qkv_bias: true
    use_rel_pos: true
    window_size: 14
    out_chans: 256
    scale_factor: 32
    input_type: fft
    freq_nums: 0.25
    prompt_type: highpass
    prompt_embed_dim: 256
    tuning_stage: 1234
    handcrafted_tune: true
    embedding_tune: true
    adaptor: adaptor
    embed_dim: 1024
    depth: 24
    num_heads: 16
    global_attn_indexes:
    - 5
    - 11
    - 17
    - 23


num_classes: 2

criterion:
  _target_: torch.nn.CrossEntropyLoss

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.0002
scheduler: 
  _target_: torch.optim.lr_scheduler.MultiStepLR
  _partial_: true
  milestones: [1]
  gamma: 0.1
