_target_: src.models.base_module.BaseLitModule

net:
  _target_: src.models.components.scnn.SCNN
  num_classes: 2
  in_channels: 3


criterion:
  _target_: torch.nn.CrossEntropyLoss

optimizer:
  _target_: torch.optim.RMSprop
  _partial_: true
  lr: 0.0001

scheduler: null