_target_: src.models.base_module.BaseLitModule

net:
  _target_: src.models.components.kappamask.KappaMask
  num_classes: 2
  in_channels: 3


criterion:
  _target_: torch.nn.CrossEntropyLoss

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.00001

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 4