defaults:
  - model_checkpoint
  # - early_stopping
  - model_summary
  - rich_progress_bar
  - _self_

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "step_{step}"
  monitor: "val/loss"
  mode: "min"
  save_last: True
  auto_insert_metric_name: False
  every_n_train_steps: 4000

# early_stopping:
#   monitor: "val/loss"
#   patience: 10
#   mode: "min"

model_summary:
  max_depth: -1
