python src/train.py experiment=cloudsen12_high_l1c/cdnetv1.yaml trainer.devices=[6]  
python src/train.py experiment=cloudsen12_high_l1c/cdnetv2.yaml trainer.devices=[6]  
python src/train.py experiment=cloudsen12_high_l1c/mcdnet.yaml trainer.devices=[6]  
python src/train.py experiment=cloudsen12_high_l1c/dbnet.yaml trainer.devices=[6]  
python src/train.py experiment=cloudsen12_high_l1c/hrcloudnet.yaml trainer.devices=[6]  
python src/train.py experiment=cloudsen12_high_l1c/kappamask.yaml trainer.devices=[6]  
python src/train.py experiment=cloudsen12_high_l1c/unetmobv2.yaml trainer.devices=[6]  
python src/train.py experiment=cloudsen12_high_l1c/scnn.yaml trainer.devices=[6]  