python src/train.py experiment=cloudsen12_high_l2a/cdnetv1.yaml trainer.devices=[6]  
python src/train.py experiment=cloudsen12_high_l2a/cdnetv2.yaml trainer.devices=[6]  
python src/train.py experiment=cloudsen12_high_l2a/mcdnet.yaml trainer.devices=[6]  
python src/train.py experiment=cloudsen12_high_l2a/dbnet.yaml trainer.devices=[6]  
python src/train.py experiment=cloudsen12_high_l2a/hrcloudnet.yaml trainer.devices=[6]  
python src/train.py experiment=cloudsen12_high_l2a/kappamask.yaml trainer.devices=[6]  
python src/train.py experiment=cloudsen12_high_l2a/unetmobv2.yaml trainer.devices=[6]  
python src/train.py experiment=cloudsen12_high_l2a/scnn.yaml trainer.devices=[6]  