python src/train.py experiment=gf12ms_whu_gf1/cdnetv1.yaml trainer.devices=[7]  
python src/train.py experiment=gf12ms_whu_gf1/cdnetv2.yaml trainer.devices=[7]  
python src/train.py experiment=gf12ms_whu_gf1/mcdnet.yaml trainer.devices=[7]  
python src/train.py experiment=gf12ms_whu_gf1/dbnet.yaml trainer.devices=[7]  
python src/train.py experiment=gf12ms_whu_gf1/hrcloudnet.yaml trainer.devices=[7]  
python src/train.py experiment=gf12ms_whu_gf1/kappamask.yaml trainer.devices=[7]  
python src/train.py experiment=gf12ms_whu_gf1/unetmobv2.yaml trainer.devices=[7]  
python src/train.py experiment=gf12ms_whu_gf1/scnn.yaml trainer.devices=[7]  