python src/train.py experiment=gf12ms_whu_gf2/cdnetv1.yaml trainer.devices=[7]  
python src/train.py experiment=gf12ms_whu_gf2/cdnetv2.yaml trainer.devices=[7]  
python src/train.py experiment=gf12ms_whu_gf2/mcdnet.yaml trainer.devices=[7]  
python src/train.py experiment=gf12ms_whu_gf2/dbnet.yaml trainer.devices=[7]  
python src/train.py experiment=gf12ms_whu_gf2/hrcloudnet.yaml trainer.devices=[7]  
python src/train.py experiment=gf12ms_whu_gf2/kappamask.yaml trainer.devices=[7]  
python src/train.py experiment=gf12ms_whu_gf2/unetmobv2.yaml trainer.devices=[7]  
python src/train.py experiment=gf12ms_whu_gf2/scnn.yaml trainer.devices=[7]  