python src/train.py experiment=hrc_whu/cdnetv1.yaml trainer.devices=[3]  
python src/train.py experiment=hrc_whu/cdnetv2.yaml trainer.devices=[3]  
python src/train.py experiment=hrc_whu/mcdnet.yaml trainer.devices=[3]  
python src/train.py experiment=hrc_whu/dbnet.yaml trainer.devices=[3]  
python src/train.py experiment=hrc_whu/hrcloudnet.yaml trainer.devices=[3]  
python src/train.py experiment=hrc_whu/kappamask.yaml trainer.devices=[3]  
python src/train.py experiment=hrc_whu/unetmobv2.yaml trainer.devices=[3]  
python src/train.py experiment=hrc_whu/scnn.yaml trainer.devices=[3]  