python src/train.py experiment=l8_biome/cdnetv1.yaml trainer.devices=[3]  
python src/train.py experiment=l8_biome/cdnetv2.yaml trainer.devices=[3]  
python src/train.py experiment=l8_biome/mcdnet.yaml trainer.devices=[3]  
python src/train.py experiment=l8_biome/dbnet.yaml trainer.devices=[3]  
python src/train.py experiment=l8_biome/hrcloudnet.yaml trainer.devices=[3]  
python src/train.py experiment=l8_biome/kappamask.yaml trainer.devices=[3]  
python src/train.py experiment=l8_biome/unetmobv2.yaml trainer.devices=[3]  
python src/train.py experiment=l8_biome/scnn.yaml trainer.devices=[3]  